apiVersion: v1
kind: Service
metadata:
  labels:
    service: credhub
  name: credhub
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  type: LoadBalancer
  selector:
    service: credhub
