apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: credhub
  name: credhub
spec:
  replicas: 1
  selector:
    matchLabels:
      service: credhub
  template:
    metadata:
      labels:
        service: credhub
    spec:
      containers:
        - env:
            - name: UAA_INTERNAL_URL
              value: http://uaa:8080/uaa
            - name: UAA_URL
              value: https://uaa.ci.miclip.io/uaa
            - name: SERVER_SSL_ENABLED
              value: "false"
          image: orangeopensource/credhub
          name: credhub
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
